application: ryoung786
version: 3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /assets
  static_dir: assets
- url: /images
  static_dir: images
- url: /old
  static_dir: athena
- url: /.*
  script: handler.py